safe:        false
auto:        true
server:      true
server_port: 4000
url: http://localhost:4000

source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         false
pygments:    true
markdown:    maruku
permalink:   /:year/:i_month/:i_day/:title

paginate: 5
